CREDENTIALS_FILE = 'telegrambotwrite-1594670249111-247d4243e67c.json'
SPREADSHEET_NAME = 'MyBudget'

CATEGORIES_WKS_NAME = 'Categories'
EXPENSE_CATEGORIES_RANGE = 'A2:A'
INCOME_CATEGORIES_RANGE = 'B2:A'

ACCOUNTS_WKS_NAME = 'Accounts'
ACCOUNT_OPTIONS_RANGE = 'F2:F'

TRANSACTIONS_WKS_NAME = 'Transactions'
TRANSACTIONS_WKS_EXPENSE_COLUMN_RANGE = 'A:E'
TRANSACTIONS_WKS_INCOME_COLUMN_RANGE = 'F:J'
TRANSACTIONS_WKS_TRANSFER_COLUMN_RANGE = 'K:P'

DEBT_WKS_NAME = 'Debts'
